import type { CanvasViewMode, ConstraintStatus, Tool } from "@/features/canvas/domain/canvasDomainModels";

const toolNames: Record<Tool, string> = {
  select: "選択",
  point: "点",
  line: "線分",
  circle: "円",
  arc: "円弧",
  freeText: "テキスト",
  centerLine: "中心線",
  horizontalCenterLine: "水平中心線",
  verticalCenterLine: "垂直中心線",
  roundHole: "丸穴",
  stitchStartPoint: "縫い始め点",
  offset: "オフセット",
  fillet: "フィレット",
  coincident: "一致",
  horizontal: "水平",
  vertical: "垂直",
  parallel: "平行",
  perpendicular: "直交",
  tangent: "接線",
  equalLength: "同長",
  angle: "角度",
  symmetric: "対称",
  pointOnLine: "直線上",
  fixed: "固定",
  distance: "距離",
  horizontalDistance: "水平距離",
  verticalDistance: "垂直距離",
  lineLineDistance: "線間距離",
  segmentLength: "線分長",
  diameter: "直径",
  radius: "半径",
  measureDistance: "距離表示",
  measureSegmentLength: "線分長表示",
  measureAngle: "角度表示",
  measureRadius: "半径表示",
  measureDiameter: "直径表示",
  measureArcSweepAngle: "円弧角表示",
};

const viewModeNames: Record<CanvasViewMode, string> = {
  editDisplay: "編集表示",
  outputPreview: "出力プレビュー",
};

const constraintStatusNames: Record<ConstraintStatus, string> = {
  unknown: "未評価",
  underConstrained: "拘束不足",
  fullyConstrained: "完全拘束",
  overConstrained: "冗長拘束",
  conflicting: "競合",
};

const appStrings = {
  common: {
    close: "閉じる",
    cancel: "キャンセル",
    details: "詳細",
  },
  document: {
    untitled: "無題プロジェクト",
  },
  error: {
    category: {
      userCorrectable: "操作を完了できません",
      operationFailure: "処理に失敗しました",
      systemInternal: "アプリ内部で問題が発生しました",
    },
    recovery: {
      reviewCurrentInputs: "現在の入力や選択内容を見直してください。",
      adjustSelectionOrTarget: "選択対象やドラッグ対象を確認してから再試行してください。",
      candidateCheckFailed: (error: unknown) => `復旧候補を確認できません: ${String(error)}`,
      restoreCompleted: "復旧用スナップショットを開きました。保存して復旧を完了してください。",
      discardCompleted: "復旧用スナップショットを破棄しました。",
      discardFailed: (error: unknown) => `復旧用スナップショットを破棄できません: ${String(error)}`,
      postponed: "復旧候補は後で確認できます。",
    },
    partLibrary: {
      loadFailed: (error: unknown) => `パーツライブラリを読み込めません: ${String(error)}`,
      saveFailed: (error: unknown) => `パーツライブラリを保存できません: ${String(error)}`,
    },
  },
  validation: {
    externalUpdate: "外部で更新されています。最新値を採用するか、入力内容を適用してください。",
    exponentNotAllowed: "指数表記は使用できません",
    ambiguousDecimal: "小数点の書式が曖昧です",
    numberRequired: "数値を入力してください",
    invalidNumber: "数値の書式が正しくありません",
    positiveNumberRequired: "0より大きい値を入力してください",
    hexColorRequired: "#RRGGBB形式で入力してください",
  },
  status: {
    loading: "読み込み中です。",
    readyToDraw: "ツールを選択して作図してください。",
    recoverySnapshotSaveFailed: (error: unknown) => `復旧用スナップショットを保存できません: ${String(error)}`,
    selectSingleArcForTangency: "両端を接線化する円弧を1つ選択してください。",
    cannotDeleteLastLayer: "最後のレイヤーは削除できません。",
    layerDeletionAffectsGeometry: (name: string) => `「${name}」を削除すると図形に影響します。`,
    layerDeletionCheckFailed: (error: unknown) => `レイヤー削除を確認できません: ${String(error)}`,
    selectGeometryForPart: "パーツ化する図形を選択してください。",
    constraintAdded: (tool: string) => `${tool}拘束を追加しました。`,
    constraintAddFailed: (error: unknown) => `拘束を追加できません: ${String(error)}`,
    specifyConstraintValue: (tool: string) => `${tool}の値を指定してください。`,
    segmentLengthConstraintFailed: (error: unknown) => `線分長を拘束できません: ${String(error)}`,
    specifyOffsetValue: "オフセットの値を指定してください。",
    specifyFilletRadius: "フィレット半径を指定してください。",
    derivedElementAddFailed: (tool: string, error: unknown) => `${tool}を追加できません: ${String(error)}`,
    remainingTargets: (tool: string, count: number) => `${tool}: あと ${count} 件の対象を選択してください。`,
    selectFilletTargets: "フィレットの対象を選択してください。",
    measurementSelected: "計測表示を選択しました。",
    dimensionConstraintSelected: "寸法拘束を選択しました。",
    constraintSelected: "拘束を選択しました。",
    stitchStartPointSelected: "縫い始め点を選択しました。",
    textSelected: "テキストを選択しました。",
    dragFilletRadius: "フィレット半径をドラッグして変更します。",
    dragControlPoint: "制御点をドラッグして移動します。",
    clickToolTarget: (tool: string) => `${tool}の対象をクリックしてください。`,
    derivedTargetUnsupported: (tool: string) => `${tool}にはこの派生要素を使用できません。`,
    arcStartPoint: "円弧の開始点をクリックします。",
    arcEndPoint: "円弧の終点をクリックします。",
    specifyNextPoint: (tool: string) => `${tool}の次の点を指定してください。`,
    arcEndAngleInvalid: "円弧の終点は開始点と異なる角度にしてください。",
    marqueeSelection: (x: string, y: string) => `矩形選択: ${x}, ${y} mm`,
    marqueeFeedback: (mode: "contained" | "crossing", count: number) =>
      `${mode === "crossing" ? "交差選択" : "包含選択"}: ${count} 件`,
    operationCompleted: "操作を完了しました。",
    selectGeometryToCopy: "コピーする図形を選択してください。",
    copiedGeometry: (count: number) => `${count} 件の図形をコピーしました。`,
    copyFailed: (error: unknown) => `コピーできません: ${String(error)}`,
    selectGeometryToCut: "切り取る図形を選択してください。",
    cutFailed: (error: unknown) => `切り取れません: ${String(error)}`,
    clipboardEmpty: "貼り付ける図形がありません。",
    selectGeometryToDuplicate: "複製する図形を選択してください。",
    workspaceReset: "レイアウトと表示補助を初期状態に戻しました。",
    partContentsSelected: (name: string) => `「${name}」の内容を選択しました。`,
    partAddedToLibrary: (name: string) => `「${name}」をパーツライブラリに登録しました。`,
    partLibraryAddFailed: (error: unknown) => `パーツライブラリに登録できません: ${String(error)}`,
    pastePositionDismissed: "貼り付け位置の選択を閉じました。",
    movePreviewCancelled: "移動プレビューを取り消しました。",
    partSelectionCleared: "パーツ選択を解除しました。",
    summaryHidden: "サマリーを非表示にしました。",
    summaryShown: "サマリーを表示しました。",
    selectPartOrigin: (name: string) => `「${name}」の原点をキャンバスでクリックしてください。`,
    layerDeletionCancelled: (name: string) => `「${name}」の削除を取り消しました。`,
  },
  accessibility: {
    cadToolbar: "CAD ツールバー",
    editSelection: "選択図形を編集",
    zoom: "ズーム",
    displayAids: "表示補助",
    showTools: "ツールを表示",
    showInspector: "インスペクタを表示",
    viewMode: "表示モード",
    moreActions: "その他の操作",
    constraintStatus: "拘束状態",
    pastePosition: "貼り付け位置",
    dismissPastePosition: "貼り付け位置を閉じる",
    dismissDrawer: "ドロワーを閉じる",
    summary: "サマリー",
  },
  toolbar: {
    drawingLayer: "作図レイヤー",
    zoomToFit: "全体表示",
    zoomOut: "縮小",
    zoomIn: "拡大",
    grid: "グリッド",
    a4Reference: "A4",
    a4Landscape: "A4横向き",
    gridSnap: "グリッドスナップ",
    pointSnap: "点スナップ",
    copySelection: "選択図形をコピー",
    pasteSelection: "コピーした図形をペースト",
    duplicateSelection: "選択図形を複製",
  },
  styles: {
    black: "黒",
    gray: "グレー",
    red: "赤",
    blue: "青",
    green: "緑",
    orange: "オレンジ",
    purple: "紫",
  },
  paste: {
    position: "貼り付け位置",
    cursor: "カーソル位置",
    nearSource: "元図形の近く",
  },
  dialog: {
    value: {
      ariaLabel: (label: string) => `${label}の値`,
      inputMethod: "値の指定方法",
      fixed: "固定値",
      parameter: "パラメータ",
      degrees: "角度 (度)",
      millimeters: "値 (mm)",
      cancel: "キャンセル",
      confirm: "確定",
    },
    derived: {
      offset: "オフセット",
      fillet: "フィレット",
      value: (kind: "offset" | "fillet") => (kind === "offset" ? "オフセット" : "フィレット"),
      filletDescription: (count: number) => `選択した ${count} 件の連続する要素にフィレットを作成します。`,
      offsetSource: "オフセット元",
      selectedRange: (count: number) => `オフセット元: 選択範囲（${count} 件）`,
      inputMethod: "入力方法",
      parameterReference: "パラメータ参照",
      millimeters: "値 (mm)",
      apply: "適用",
      scopeNames: {
        singleElement: "単独要素",
        selectedRange: "選択範囲",
        closedContour: "閉じた輪郭",
      },
      parameterValue: (name: string, value: number) => `${name}（${value} mm）`,
    },
    layerDeletion: {
      ariaLabel: "レイヤー削除の確認",
      title: (name: string) => `「${name}」を削除しますか？`,
      impact: (count: number) => `${count} 件の図形または派生要素がこのレイヤーを参照しています。`,
      cancel: "キャンセル",
      delete: "削除",
    },
    textEntry: { cancel: "キャンセル", apply: "適用" },
  },
  palette: {
    groupNames: { drawing: "作図", derived: "派生", constraint: "拘束", dimension: "寸法", measurement: "計測" },
    ariaLabel: "ツールパレット",
    title: "ツール",
    subtitle: "補助パレット",
    display: "ツール表示",
    showDetailed: "詳細ツールを表示",
    showBasicOnly: "基本ツールだけを表示",
    lineStyle: "型紙線種",
    lineStyleAria: "型紙線種",
    applyToSelection: "選択へ適用",
    roundHole: "丸穴",
    roundHoleKind: "丸穴の用途",
    roundHoleDiameter: "丸穴の直径 (mm)",
    roundHoleKinds: {
      keyRing: "キーリング穴",
      rivet: "カシメ穴",
      snapFastener: "ジャンパーホック穴",
      decorative: "装飾穴",
    },
    activeDetailedTool: "使用中の詳細ツール",
  },
  workbench: {
    selection: "選択",
    constraints: "拘束",
    parameters: "パラメータ",
    none: "なし",
    noSelection: "選択なし",
    selectOnCanvas: "キャンバス上の図形を選択します。",
    noConstraints: "拘束なし",
    noConstraintDescription: "拘束はありません。",
    overConstrained: "過拘束",
    unresolved: "未解決",
    evaluated: "評価済み",
    noParameters: "パラメータなし",
    unusedParameters: "未使用 0 件",
    parameterUsage: (used: number, unused: number) => `使用 ${used} 件 / 未使用 ${unused} 件`,
    itemCount: (count: number) => `${count} 件`,
    layer: (name: string) => `レイヤー: ${name}`,
    shape: "図形",
  },
  menu: {
    section: {
      file: "ファイル",
      edit: "編集",
      drawing: "作図",
      constraint: "拘束",
      measurement: "計測",
      layer: "レイヤー",
      view: "表示",
    },
    item: {
      about: "KawaCADについて",
      openSourceLicenses: "OSSライセンス…",
      new: "新規プロジェクト",
      open: "開く…",
      save: "保存",
      saveAs: "別名で保存…",
      exportPDF: "PDF出力…",
      directPrint: "直接印刷…",
      undo: "元に戻す",
      redo: "やり直す",
      cut: "カット",
      copy: "コピー",
      paste: "ペースト",
      duplicate: "複製",
      delete: "削除",
      selectAll: "すべてを選択",
      findInspector: "インスペクタ内を検索",
      smoothArcTangencies: "両端を接線化（試作）",
      measureSegmentLength: "線分長表示",
      toggleInspector: "インスペクタを表示／隠す",
      toggleBottomWorkbench: "サマリーを表示／隠す",
      toggleA4Orientation: "A4向きを切り替え",
      resetLayout: "レイアウトをリセット",
      reload: "再読み込み",
    },
  },
  canvas: {
    outputPreview: "出力プレビュー",
    editDisplay: "編集表示",
    partOriginSelection: "パーツ原点を選択中",
    filletDraft: (count: number, closed: boolean) =>
      `フィレット対象 ${count} 件、${closed ? "閉じた輪郭" : "開いた輪郭"}`,
    arcStartSelection: "円弧の開始点を選択中",
    arcEndSelection: "円弧の終点を選択中",
    constraintTargetSelection: (count: number) => `拘束対象を ${count} 件選択中`,
    drawingNextPoint: "作図の次の点を選択中",
    drawingWaiting: "作図待機中",
    emptyTitle: "作図を始めましょう",
    emptyBody: "ツールを選択してキャンバスをクリックしてください。",
    dragMove: (count: number) => `${count} 件を移動中`,
    dragCopy: (count: number) => `${count} 件を複製中`,
    snapOff: "SNAP OFF",
    origin: "原点",
    scaleGuide: "50 mm",
    ariaLabel: "型紙作図キャンバス",
    editText: "テキストを編集",
    constraint: "拘束",
    interactionSummary: (tool: string, mode: string, selected: number, targets: number, description: string) =>
      `${tool}、${mode}、選択 ${selected} 件、拘束対象 ${targets} 件、${description}`,
  },
  toolbarMetrics: {
    zoom: (percent: number) => `倍率 ${percent}%`,
  },
  contextMenu: {
    convertMeasurement: "寸法拘束へ変換",
    delete: "削除",
    editText: "テキストを編集",
    copy: "コピー",
    duplicate: "複製",
    smoothArcTangencies: "両端を接線化（試作）",
    paste: "貼り付け",
    selectAll: "すべてを選択",
  },
  header: {
    projectNameRequired: "プロジェクト名を入力してください。",
    projectName: "プロジェクト名",
    useLatestValue: "最新値を使う",
    applyInput: "入力内容を適用",
  },
  resize: { paletteWidth: "ツールパレットの幅" },
  inspector: {
    tabs: { selection: "選択", layers: "レイヤー", styles: "共有スタイル", parameters: "パラメータ", parts: "パーツ" },
    ariaLabel: "インスペクタ",
    tabList: "インスペクタ項目",
    title: "インスペクタ",
    selectionSummary: (count: number) => `${count} 件を選択中`,
    selectedConstraint: "拘束を選択中",
    selectedMeasurement: "計測表示を選択中",
    selectedStitchStart: "縫い始め点を選択中",
    selectedText: "テキストを選択中",
    selectionChanged: "選択が変更されました。",
    showSelection: "選択を表示",
    noneSelected: "選択なし",
    selection: "選択",
    selectedGeometry: "図形",
    selectedLayer: "レイヤー",
    bulkStyle: "選択図形の共有線種",
    applyBulkStyle: "選択へ適用",
    createPartFromSelection: "選択図形からパーツを作成",
    nothingSelected: "何も選択されていません。",
    constraint: "拘束",
    value: "値",
    measurementAndNotes: "計測と注記",
    annotationEdit: "注記を編集",
    annotation: "注記",
    display: "表示",
    edit: "編集",
    layers: "レイヤー",
    drawingLayer: "作図レイヤー",
    layerSearch: "レイヤーを検索",
    includeInOutput: (name: string) => `${name} を出力対象に含める`,
    outputTarget: "出力対象",
    addLayer: "レイヤーを追加",
    sharedStyles: "共有線種",
    sharedStyleSearch: "共有スタイルを検索",
    styleName: "線種名",
    newStyle: "新規線種",
    name: "名称",
    addSharedStyle: "共有線種を追加",
    parameters: "パラメータ",
    add: "追加",
    parameterSearch: "パラメータを検索",
    parts: "パーツ",
    noParts: "パーツはありません。",
    alignDescription: "配置対象を選択して境界を揃えます。",
    alignLeft: "左揃え",
    alignCenter: "横中央",
    alignRight: "右揃え",
    alignTop: "上揃え",
    alignBottom: "下揃え",
    distributeHorizontal: "水平に均等配置",
    distributeVertical: "垂直に均等配置",
    partLibrary: "パーツライブラリ",
    place: "配置",
    noRegisteredParts: "登録済みのパーツはありません。",
    document: "ドキュメント",
    viewMode: "表示モード",
    activeLayer: "作図レイヤー",
    visibleGeometry: "表示図形",
    constraintCount: "拘束数",
    parameterCount: "パラメータ数",
    fixedValue: "固定値",
    millimeters: "値 (mm)",
    degrees: "度",
    measurementConstraint: "寸法拘束へ変換",
    stitchStartPoint: "縫い始め点",
    targetGeometry: "対象図形",
    content: "内容",
    textContent: "テキスト内容",
    textX: "テキスト X (mm)",
    textY: "テキスト Y (mm)",
    fontSize: "フォントサイズ (mm)",
    parameterName: "名前",
    parameterMemo: "メモ",
    unitMillimeter: "ミリメートル",
    colorPreset: "色プリセット",
    custom: "カスタム",
    color: "色",
    lineWidthPreset: "線幅プリセット",
    lineWidth: "線幅",
    lineStyle: "線種",
    lineStyles: { solid: "実線", dashed: "破線", dotted: "点線", construction: "補助線" },
    offsetElement: "オフセット線",
    filletElement: "フィレット",
    distance: "距離 (mm)",
    radius: "半径 (mm)",
    sourceElements: (count: number) => `元図形 ${count}`,
    layer: "レイヤー",
    noValue: "なし",
    direction: "方向",
    directions: { left: "左側", right: "右側", inward: "内側", outward: "外側" },
    reverseDirection: "方向を反転",
    geometry: "図形",
    smoothArcTangencies: "円弧接線を滑らかに",
    derived: (kind: string) => kind,
    dimension: "寸法",
    diameter: "直径 (mm)",
    segmentLength: "線分長 (mm)",
    startAngle: "開始角 (度)",
    sweepAngle: "掃引角 (度)",
    setCurrentLengthConstraint: "現在の長さを拘束",
    partNameField: "名前",
    quantity: "数量",
    arrangementTarget: "配置対象",
    originX: "原点 X (mm)",
    originY: "原点 Y (mm)",
    selectContents: "内容を選択",
    specifyOrigin: "原点を指定",
    libraryAdd: "ライブラリへ追加",
    nameOf: (name: string) => `${name} の名前`,
    valueOf: (name: string) => `${name} の値 (mm)`,
    memoOf: (name: string) => `${name} のメモ`,
    configurationOf: (name: string) => `${name} の構成`,
    outputOf: (name: string) => `${name} を出力対象に含める`,
    originXOf: (name: string) => `${name} の原点 X (mm)`,
    originYOf: (name: string) => `${name} の原点 Y (mm)`,
    derivedSourceCount: (count: number) => `元図形 ${count}`,
    copyOf: (name: string) => `${name}のコピー`,
    derivedValue: (kind: string, label: string) => `${kind}の${label}`,
    geometryCount: {
      outline: (count: number) => `外形 ${count}`,
      holes: (count: number) => `穴 ${count}`,
      derived: (count: number) => `派生 ${count}`,
      text: (count: number) => `テキスト ${count}`,
      measurement: (count: number) => `計測 ${count}`,
    },
    parameter: "パラメータ",
    operationUpdated: (kind: string) => `${kind}を更新しました。`,
    parameterUpdated: (name: string) => `${name} を更新しました。`,
    roundHoleKind: "丸穴用途",
    constraintValue: (degrees: boolean) => `拘束値 (${degrees ? "度" : "mm"})`,
    parameterLinked: (kind: string) => `${kind}をパラメータに関連付けました。`,
    parameterReference: "パラメータ参照",
    selectGeometry: "選択図形",
    partName: "パーツ名",
    partVisibility: "パーツ表示",
    partOriginX: (name: string) => `${name} の原点 X (mm)`,
    partOriginY: (name: string) => `${name} の原点 Y (mm)`,
    partConfiguration: (name: string) => `${name} の構成`,
    partNameFor: (name: string) => `${name} の名前`,
    addSelection: "選択を追加",
    removeSelection: "選択を除外",
    setSelectionAsOutline: "選択を外形に設定",
    align: "整列",
    distribute: "均等配置",
    detach: "解除",
    unchanged: "変更なし",
    operationMessage: {
      constraintDeleted: "拘束を削除しました。",
      offsetUpdated: "オフセット線を更新しました。",
      filletUpdated: "フィレットを更新しました。",
      roundHoleDiameterUpdated: "丸穴の直径を更新しました。",
      roundHoleKindUpdated: "丸穴用途を更新しました。",
      segmentLengthUpdated: "線分長を更新しました。",
      circleRadiusUpdated: "円の半径を更新しました。",
      currentLengthConstrained: "現在の長さを拘束",
      quantity: "数量",
      arrangementTarget: "配置対象",
      originX: "原点 X (mm)",
      originY: "原点 Y (mm)",
      outline: "外形",
      holes: "穴",
      derivedCount: "派生",
      textCount: "テキスト",
      measurementCount: "計測",
      selectContents: "内容を選択",
      specifyOrigin: "原点を指定",
      libraryAdd: "ライブラリへ追加",
      copySuffix: "のコピー",
      unitCount: (count: number) => `${count} 件`,
      changeAngle: "角度を変更",
      changeDimension: "寸法を変更",
      dimensionMillimeters: "寸法 (mm)",
      angleDegrees: "角度 (度)",
      constraintUpdated: "拘束値を更新しました。",
      constraintParameterUpdated: "拘束パラメータを更新しました。",
      measurementUpdated: "計測表示を更新しました。",
      textUpdated: "テキストを更新しました。",
      parameterDeleted: (name: string) => `${name} を削除しました。`,
      sharedStyleDeleted: "共有線種を削除しました。",
      sharedStyleUpdated: "共有線種を更新しました。",
      sharedStyleAdded: "共有線種を追加しました。",
      layerVisibleUpdated: "レイヤー表示を更新しました。",
      layerOutputUpdated: "レイヤーの出力対象を更新しました。",
      layerStyleUpdated: "レイヤー線種を更新しました。",
      partOutputUpdated: "パーツの出力対象を更新しました。",
      partOriginUpdated: "パーツ原点を更新しました。",
      partAdded: "選択図形をパーツへ追加しました。",
      partRemoved: "選択図形をパーツから除外しました。",
      outlineUpdated: "パーツ外形を更新しました。",
      partNameUpdated: "パーツ名を更新しました。",
      partVisibilityUpdated: "パーツ表示を更新しました。",
      partMoved: "パーツを移動しました。",
      partDuplicated: "パーツを複製しました。",
      partDetached: "パーツを解除しました。",
      derivedLayerUpdated: "派生要素のレイヤーを更新しました。",
      derivedStyleUpdated: "派生要素の線種を更新しました。",
      offsetDirectionUpdated: "オフセット方向を更新しました。",
      geometryLayerUpdated: "図形レイヤーを更新しました。",
      geometryStyleUpdated: "図形線種を更新しました。",
      arcUpdated: "円弧を更新しました。",
      arcTangenciesUpdated: "円弧接線を滑らかに調整しました。",
      annotationUpdated: "注記を更新しました。",
      annotationDeleted: "計測表示を削除しました。",
      textDeleted: "テキストを削除しました。",
      layerDeleted: "レイヤーを削除しました。",
    },
    styleNameEdit: "線種名を変更",
  },
  app: {
    productName: "KawaCAD",
    fileFilterName: "KawaCAD project",
    paperPortrait: "A4 Portrait",
    paperLandscape: "A4 Landscape",
    viewModeChanged: (output: boolean) => (output ? "出力プレビューに切り替えました。" : "編集表示に切り替えました。"),
    a4OrientationChanged: (landscape: boolean) => (landscape ? "A4横向きに変更しました。" : "A4縦向きに変更しました。"),
    documentNameUpdated: "プロジェクト名を更新しました。",
    selectGeometry: "図形を選択してください。",
    clickTarget: (tool: string) => `${tool}: 対象をクリックしてください。`,
    saved: "プロジェクトを保存しました。",
    reloaded: "ドキュメントを再読み込みしました。",
    undone: "取り消しました。",
    redone: "やり直しました。",
    smoothTangencies: "両端を接線化しました（試作）。",
    addLayerTitle: "レイヤーを追加",
    layerName: "レイヤー名",
    newLayer: "新規レイヤー",
    layerAdded: "レイヤーを追加しました。",
    layerDeleted: "レイヤーを削除しました。",
    createPartTitle: "パーツを作成",
    partName: "パーツ名",
    newPart: "新規パーツ",
    partCreated: "パーツを作成しました。",
    addParameterTitle: "パラメータを追加",
    parameterName: "パラメータ名",
    parameterWidth: "幅",
    parameterAdded: "パラメータを追加しました。",
    renameLayerTitle: "レイヤー名を変更",
    layerNameUpdated: "レイヤー名を更新しました。",
    partQuantityTitle: "パーツ数量",
    partQuantity: "数量",
    partQuantityUpdated: "パーツ数量を更新しました。",
    styleUpdated: "選択図形の線種を更新しました。",
    entityCreated: (tool: string) => `${tool}を作成しました。`,
    dimensionConstraintAdded: "寸法拘束を追加しました。",
    currentSegmentLengthConstrained: "現在の線分長を拘束しました。",
    measurementAdded: (tool: string) => `${tool}を追加しました。`,
    noOffsetTarget: "オフセット対象がありません。",
    filletSourceRequired: "フィレット元を2件以上選択してください。",
    offsetAdded: "オフセットを追加しました。",
    filletUpdated: "フィレットを更新しました。",
    filletAdded: "フィレットを追加しました。",
    partOriginSet: "パーツ原点を設定しました。",
    roundHoleCreated: "丸穴を作成しました。",
    invalidRoundHoleDiameter: "丸穴の直径には正の有限値を入力してください。",
    stitchStartPointPlaced: "縫い始め点を配置しました。",
    addAnnotationTitle: "注記を追加",
    annotation: "注記",
    textAdded: "テキストを追加しました。",
    duplicatePreview: "複製プレビュー中",
    movePreview: "移動プレビュー中",
    preview: "プレビュー中",
    geometryDuplicated: "選択図形を複製しました。",
    geometryMoved: "選択図形を移動しました。",
    filletRadiusUpdated: "フィレット半径を更新しました。",
    controlPointMoved: "制御点を移動しました。",
    measurementMoved: "計測表示を移動しました。",
    dimensionMoved: "寸法拘束の表示を移動しました。",
    textMoved: "テキストを移動しました。",
    measurementDeleted: "計測表示を削除しました。",
    stitchStartPointDeleted: "縫い始め点を削除しました。",
    constraintDeleted: "拘束を削除しました。",
    textDeleted: "テキストを削除しました。",
    geometryDeleted: "選択図形を削除しました。",
    geometryCut: "選択図形を切り取りました。",
    geometryPasted: "コピーした図形を貼り付けました。",
    pastePositionChanged: "貼り付け位置を変更しました。",
    libraryPartPlaced: (name: string) => `「${name}」をライブラリから配置しました。`,
    alignmentUpdated: "パーツを整列しました。",
    distributionUpdated: "パーツを均等配置しました。",
    measurementConverted: "計測表示を寸法拘束へ変換しました。",
    measurementConvertedShort: "計測表示を寸法拘束に変換しました。",
    dirtyChanges: "未保存の変更があります。",
    saveAndCloseQuestion: "未保存の変更があります。保存して閉じますか？",
    discardAndCloseQuestion: "未保存の変更があります。保存せずに閉じますか？",
    saveAndClose: "保存して閉じる",
    discardChanges: "保存しない",
    closeWithoutSaving: "保存せずに閉じる",
    cancel: "キャンセル",
    saveAndContinue: "保存して続行",
    continueWithoutSaving: "保存せずに続行",
    newProjectAction: "新規プロジェクトの作成",
    newProjectOpen: "新規プロジェクト",
    newProjectCreated: "新規プロジェクトを作成しました。",
    openOtherProjectAction: "別のプロジェクトを開く操作",
    projectOpened: "プロジェクトを開きました。",
    saveContinueQuestion: (action: string) => `未保存の変更があります。保存して${action}を続行しますか？`,
    discardContinueQuestion: (action: string) => `未保存の変更があります。保存せずに${action}を続行しますか？`,
    untitled: "無題プロジェクト",
    undoRedo: (undo: boolean) => (undo ? "取り消しました。" : "やり直しました。"),
    recoveryAria: "復旧候補",
    recoveryNotice: (name: string) => `「${name}」の復旧用スナップショットがあります。`,
    recoveryOriginal: "保存前の変更を復元できます。",
    restore: "復元",
    discard: "破棄",
    later: "後で",
    toolDrawer: "ツール",
    statusSummaryHide: "サマリーを隠す",
    statusSummaryShow: "サマリーを表示",
    hud: (zoom: number, selected: number) => `${zoom}% · ${selected} 選択`,
    statusGeometry: (count: number) => `${count} 図形`,
    statusSelection: (count: number) => `${count} 選択`,
    statusNoSelection: "選択なし",
    statusCoordinates: (x: number, y: number) => `座標 ${x.toFixed(1)}, ${y.toFixed(1)}`,
    statusNoCoordinates: "座標 —",
    outputWarnings: (count: number) => `出力プレビュー: 警告 ${count} 件`,
    outputPages: (count: number) => `出力プレビュー: ${count} ページ`,
    unsaved: "未保存",
    unsavedChanges: "未保存の変更あり",
    savedState: "保存済み",
  },
  toolNames,
  constraintLabels: {
    lineLineDistance: "線線距離",
  },
  constraintKindNames: {
    coincident: toolNames.coincident,
    horizontal: toolNames.horizontal,
    vertical: toolNames.vertical,
    parallel: toolNames.parallel,
    perpendicular: toolNames.perpendicular,
    tangent: toolNames.tangent,
    equalSegmentLength: toolNames.equalLength,
    angle: toolNames.angle,
    symmetric: toolNames.symmetric,
    pointOnLine: toolNames.pointOnLine,
    fixed: toolNames.fixed,
    distance: toolNames.distance,
    horizontalDistance: toolNames.horizontalDistance,
    verticalDistance: toolNames.verticalDistance,
    lineLineDistance: toolNames.lineLineDistance,
    segmentLength: toolNames.segmentLength,
    diameter: toolNames.diameter,
    radius: toolNames.radius,
  },
  measurementKindNames: {
    distance: toolNames.measureDistance,
    segmentLength: toolNames.measureSegmentLength,
    angle: toolNames.measureAngle,
    radius: toolNames.measureRadius,
    diameter: toolNames.measureDiameter,
    arcSweepAngle: toolNames.measureArcSweepAngle,
  },
  viewModeNames,
  constraintStatusNames,
} as const;

/** Common semantic keys shared with Swift's Localizable.strings. Platform-only
 * copy remains in each catalog, while this map makes the intentionally shared
 * surface executable and reviewable. */
export const sharedLocalizationKeyMap = {
  "app.document.untitled": "app.untitled",
  "tool.select": "toolNames.select",
  "tool.point": "toolNames.point",
  "tool.line": "toolNames.line",
  "tool.circle": "toolNames.circle",
  "tool.round_hole": "toolNames.roundHole",
  "tool.arc": "toolNames.arc",
  "tool.stitch_start_point": "toolNames.stitchStartPoint",
  "tool.center_line": "toolNames.centerLine",
  "tool.horizontal_center_line": "toolNames.horizontalCenterLine",
  "tool.vertical_center_line": "toolNames.verticalCenterLine",
  "tool.coincident": "toolNames.coincident",
  "tool.horizontal": "toolNames.horizontal",
  "tool.vertical": "toolNames.vertical",
  "tool.parallel": "toolNames.parallel",
  "tool.perpendicular": "toolNames.perpendicular",
  "tool.tangent": "toolNames.tangent",
  "tool.equal_length": "toolNames.equalLength",
  "tool.angle": "toolNames.angle",
  "tool.symmetric": "toolNames.symmetric",
  "tool.point_on_line": "toolNames.pointOnLine",
  "tool.fixed": "toolNames.fixed",
  "tool.distance": "toolNames.distance",
  "tool.horizontal_distance": "toolNames.horizontalDistance",
  "tool.vertical_distance": "toolNames.verticalDistance",
  "tool.line_line_distance": "constraintLabels.lineLineDistance",
  "tool.segment_length": "toolNames.segmentLength",
  "tool.diameter": "toolNames.diameter",
  "tool.radius": "toolNames.radius",
  "tool.offset": "toolNames.offset",
  "tool.fillet": "toolNames.fillet",
  "tool.free_text": "toolNames.freeText",
  "tool.measure_distance": "toolNames.measureDistance",
  "tool.measure_segment_length": "toolNames.measureSegmentLength",
  "tool.measure_angle": "toolNames.measureAngle",
  "tool.measure_radius": "toolNames.measureRadius",
  "tool.measure_diameter": "toolNames.measureDiameter",
  "tool.measure_arc_sweep_angle": "toolNames.measureArcSweepAngle",
  "view_mode.edit_display": "viewModeNames.editDisplay",
  "view_mode.output_preview": "viewModeNames.outputPreview",
  "constraint_status.unknown": "constraintStatusNames.unknown",
  "constraint_status.under_constrained": "constraintStatusNames.underConstrained",
  "constraint_status.fully_constrained": "constraintStatusNames.fullyConstrained",
  "constraint_status.over_constrained": "constraintStatusNames.overConstrained",
  "constraint_status.conflicting": "constraintStatusNames.conflicting",
} as const;

export { appStrings };
