import type { CanvasViewMode, ConstraintStatus, Tool } from "@/features/canvas/domain/canvasDomainModels";

const toolNames: Record<Tool, string> = {
  select: "選択",
  point: "点",
  line: "線分",
  circle: "円",
  arc: "円弧",
  freeText: "テキスト",
  centerLine: "中心線",
  horizontalCenterLine: "水平中心線",
  verticalCenterLine: "垂直中心線",
  roundHole: "丸穴",
  stitchStartPoint: "縫い始め点",
  offset: "オフセット",
  fillet: "フィレット",
  coincident: "一致",
  horizontal: "水平",
  vertical: "垂直",
  parallel: "平行",
  perpendicular: "直交",
  tangent: "接線",
  equalLength: "同長",
  angle: "角度",
  symmetric: "対称",
  pointOnLine: "直線上",
  fixed: "固定",
  distance: "距離",
  horizontalDistance: "水平距離",
  verticalDistance: "垂直距離",
  lineLineDistance: "線線距離",
  segmentLength: "線分長",
  diameter: "直径",
  radius: "半径",
  measureDistance: "距離表示",
  measureSegmentLength: "線分長表示",
  measureAngle: "角度表示",
  measureRadius: "半径表示",
  measureDiameter: "直径表示",
  measureArcSweepAngle: "円弧角表示",
};

const toolHints: Record<Tool, string> = {
  select: "図形、拘束マーク、計測表示などをクリックして選択します",
  point: "点を置く位置をクリックします",
  line: "線分の始点をクリックします",
  circle: "円の中心をクリックします",
  arc: "円弧の中心をクリックします",
  freeText: "テキストを配置する位置をクリックします",
  centerLine: "中心線の始点をクリックします",
  horizontalCenterLine: "水平中心線の始点をクリックします",
  verticalCenterLine: "垂直中心線の始点をクリックします",
  roundHole: "丸穴の中心をクリックします",
  stitchStartPoint: "縫い始め点を置く縫い線をクリックします",
  offset: "オフセット元をクリックします（複数選択時は選択範囲を使います）",
  fillet: "フィレットする接続線分を2本以上クリックします",
  coincident: "一致させる点エンティティを2つクリックします",
  horizontal: "水平にする線分をクリックします",
  vertical: "垂直にする線分をクリックします",
  parallel: "平行にする線分を2つクリックします",
  perpendicular: "直交させる線分を2つクリックします",
  tangent: "滑らかに接続する線分端点と円弧端点をクリックします",
  equalLength: "同じ長さにする線分を2つクリックします",
  angle: "角度を固定する線分2つ、または円弧をクリックします",
  symmetric: "対称にする点2つと対称軸を順にクリックします",
  pointOnLine: "直線上に保つ点と線分をクリックします",
  fixed: "固定する点または中心点をクリックします",
  distance: "距離を固定する2点、または点と線分をクリックします",
  horizontalDistance: "2点間の水平距離を固定する点を2つクリックします",
  verticalDistance: "2点間の垂直距離を固定する点を2つクリックします",
  lineLineDistance: "支持直線間の距離を固定する線分を2つクリックします",
  segmentLength: "長さを固定する線分をクリックします",
  diameter: "直径を固定する円をクリックします",
  radius: "半径を固定する円または円弧をクリックします",
  measureDistance: "表示する2点距離をクリックします",
  measureSegmentLength: "表示する線分長の線分をクリックします",
  measureAngle: "表示する角度の線分を2つクリックします",
  measureRadius: "表示する半径の円または円弧をクリックします",
  measureDiameter: "表示する直径の円をクリックします",
  measureArcSweepAngle: "表示する掃引角の円弧をクリックします",
};

const viewModeNames: Record<CanvasViewMode, string> = {
  editDisplay: "編集表示",
  outputPreview: "出力プレビュー",
};

const constraintStatus: Record<ConstraintStatus, string> = {
  unknown: "未評価",
  underConstrained: "拘束不足",
  fullyConstrained: "完全拘束",
  overConstrained: "冗長拘束",
  conflicting: "競合",
};

const appStrings = {
  common: {
    close: "閉じる",
    cancel: "キャンセル",
    details: "詳細",
    retry: "再試行",
  },
  document: {
    untitled: "無題プロジェクト",
  },
  output: {
    pdfTitle: "PDF",
    directPrintTitle: "直接印刷",
    pdfHelp: "設定変更に追従して、実際に出力されるページ構成をここで確認します。",
    directPrintHelp: "A4固定・100%実寸・片面で、印刷ダイアログを表示せずに送信します。",
    destination: "出力先",
    status: "状態",
    warningLabel: "出力警告",
    pdf: "PDF",
    directPrint: "直接印刷",
    paper: "用紙",
    paperValue: "A4",
    scale: "倍率",
    scaleActualSize: "100% 実寸",
    pageCount: "総ページ数",
    calculating: "算出中",
    pages: (count: number) => `${count}ページ`,
    settings: "出力設定",
    printer: "プリンタ",
    choosePrinter: "選択してください",
    includeDimensions: "寸法数値を出力に含める",
    includeScaleGuide: "50mmガイドを出力に含める",
    warningCount: (count: number) => `警告 ${count} 件`,
    noOutput: "出力ページがありません。形状または設定を確認してください。",
    buildLoading: "最新の出力内容を構築中です。",
    ready: "出力可能",
    saving: "PDF保存中…",
    saveNext: "保存へ進む",
    warningSaveNext: "警告を確認して保存へ進む",
    printing: "印刷中…",
    printNext: "印刷へ進む",
    warningPrintNext: "警告を確認して印刷へ進む",
    finalPreview: "最終プレビュー",
    generating: "出力内容を生成中…",
    updating: "プレビューを更新しています",
    saveFailed: (error: unknown) => `PDFを保存できません: ${String(error)}`,
    buildFailed: (error: string) => `出力内容を生成できません: ${error}`,
    exported: (path: string) => `PDFを保存しました: ${path}`,
    directPrintStarted: "直接印刷を開始しました。",
    directPrintUnavailable: "直接印刷は利用できません。",
    directPrintUnavailableWithReason: (error: unknown) => `直接印刷を利用できません: ${String(error)}`,
    directPrintFailedWithReason: (error: unknown) => `印刷ジョブを開始できません: ${String(error)}`,
    printerUnavailable: "利用可能なプリンタがありません。",
    pdfPageLabel: (pageNumber: number) => `PDF ${pageNumber}ページ目`,
  },
  error: {
    category: {
      userCorrectable: "操作を完了できません",
      operationFailure: "処理に失敗しました",
      systemInternal: "アプリ内部で問題が発生しました",
    },
    recovery: {
      reviewCurrentInputs: "現在の入力や選択内容を見直してください。",
      adjustSelectionOrTarget: "選択対象やドラッグ対象を確認してから再試行してください。",
      candidateCheckFailed: (error: unknown) => `復旧候補を確認できません: ${String(error)}`,
      revealFailed: (error: unknown) => `復旧候補の保存場所を表示できません: ${String(error)}`,
      restoreCompleted: "自動復旧データを開きました。保存して内容を確定してください。",
      discardCompleted: "復旧用スナップショットを破棄しました。",
      discardFailed: (error: unknown) => `復旧用スナップショットを破棄できません: ${String(error)}`,
      postponed: "復旧候補は後で確認できます。",
    },
    partLibrary: {
      loadFailed: (error: unknown) => `パーツライブラリを読み込めません: ${String(error)}`,
      saveFailed: (error: unknown) => `パーツライブラリを保存できません: ${String(error)}`,
    },
  },
  validation: {
    externalUpdate: "外部で更新されています。最新値を採用するか、入力内容を適用してください。",
    exponentNotAllowed: "指数表記は使用できません",
    ambiguousDecimal: "小数点の書式が曖昧です",
    numberRequired: "数値を入力してください",
    invalidNumber: "数値の書式が正しくありません",
    positiveNumberRequired: "0より大きい値を入力してください",
    hexColorRequired: "#RRGGBB形式で入力してください",
  },
  status: {
    loading: "読み込み中です。",
    readyToDraw: "ツールを選択して作図してください。",
    offsetDistance: "オフセット距離",
    lineWidth: "線幅",
    recoverySnapshotSaveFailed: (error: unknown) => `復旧用スナップショットを保存できません: ${String(error)}`,
    selectSingleArcForTangency: "両端を接線化する円弧を1つ選択してください。",
    cannotDeleteLastLayer: "最後のレイヤーは削除できません。",
    layerDeletionAffectsGeometry: (name: string) => `「${name}」を削除すると図形に影響します。`,
    layerDeletionCheckFailed: (error: unknown) => `レイヤー削除を確認できません: ${String(error)}`,
    selectGeometryForPart: "パーツ化する図形を選択してください。",
    constraintAdded: (tool: string) => `${tool}拘束を追加しました。`,
    constraintAddFailed: (error: unknown) => `拘束を追加できません: ${String(error)}`,
    specifyConstraintValue: (tool: string) => `${tool}の値を指定してください。`,
    segmentLengthConstraintFailed: (error: unknown) => `線分長を拘束できません: ${String(error)}`,
    specifyOffsetValue: "オフセットの値を指定してください。",
    specifyFilletRadius: "フィレット半径を指定してください。",
    derivedElementAddFailed: (tool: string, error: unknown) => `${tool}を追加できません: ${String(error)}`,
    remainingTargets: (tool: string, count: number) => `${tool}: あと ${count} 件の対象を選択してください。`,
    selectFilletTargets: "フィレットの対象を選択してください。",
    measurementSelected: "計測表示を選択しました。",
    dimensionConstraintSelected: "寸法拘束を選択しました。",
    constraintSelected: "拘束を選択しました。",
    stitchStartPointSelected: "縫い始め点を選択しました。",
    textSelected: "テキストを選択しました。",
    dragFilletRadius: "フィレット半径をドラッグして変更します。",
    dragControlPoint: "制御点をドラッグして移動します。",
    clickToolTarget: (tool: string) => `${tool}の対象をクリックしてください。`,
    derivedTargetUnsupported: (tool: string) => `${tool}にはこの派生要素を使用できません。`,
    arcStartPoint: "円弧の開始点をクリックします。",
    arcEndPoint: "円弧の終点をクリックします。",
    specifyNextPoint: (tool: string) => `${tool}の次の点を指定してください。`,
    arcEndAngleInvalid: "円弧の終点は開始点と異なる角度にしてください。",
    marqueeSelection: (x: string, y: string) => `矩形選択: ${x}, ${y} mm`,
    marqueeFeedback: (mode: "contained" | "crossing", count: number) =>
      `${mode === "crossing" ? "交差する図形を含めて選択" : "完全に含まれる図形を選択"}: ${count}件`,
    operationCompleted: "操作を完了しました。",
    selectGeometryToCopy: "コピーする図形を選択してください。",
    copiedGeometry: (count: number) => `${count} 件の図形をコピーしました。`,
    copyFailed: (error: unknown) => `コピーできません: ${String(error)}`,
    selectGeometryToCut: "切り取る図形を選択してください。",
    cutFailed: (error: unknown) => `切り取れません: ${String(error)}`,
    clipboardEmpty: "貼り付ける図形がありません。",
    selectGeometryToDuplicate: "複製する図形を選択してください。",
    workspaceReset: "レイアウトと表示補助を初期状態に戻しました。",
    partContentsSelected: (name: string) => `「${name}」の内容を選択しました。`,
    partAddedToLibrary: (name: string) => `「${name}」をパーツライブラリに登録しました。`,
    partLibraryAddFailed: (error: unknown) => `パーツライブラリに登録できません: ${String(error)}`,
    pastePositionDismissed: "ペーストオプションを閉じました。",
    movePreviewCancelled: "移動プレビューを取り消しました。",
    partSelectionCleared: "パーツ選択を解除しました。",
    summaryHidden: "サマリーを非表示にしました。",
    summaryShown: "サマリーを表示しました。",
    selectPartOrigin: (name: string) => `「${name}」の原点をキャンバスでクリックしてください。`,
    layerDeletionCancelled: (name: string) => `「${name}」の削除を取り消しました。`,
  },
  accessibility: {
    cadToolbar: "CAD ツールバー",
    editSelection: "選択図形を編集",
    zoom: "ズーム",
    displayAids: "表示補助",
    showTools: "ツールを表示",
    showInspector: "インスペクタを表示",
    viewMode: "表示モード",
    moreActions: "その他の操作",
    constraintStatus: "拘束状態",
    pastePosition: "ペーストオプション",
    dismissPastePosition: "ペーストオプションを閉じる",
    dismissDrawer: "ドロワーを閉じる",
    summary: "サマリー",
  },
  toolbar: {
    drawingLayer: "作図レイヤー",
    zoomToFit: "全体表示",
    zoomOut: "縮小",
    zoomIn: "拡大",
    grid: "グリッド",
    a4Reference: "A4",
    a4Landscape: "A4横向き",
    gridSnap: "グリッドスナップ",
    pointSnap: "点スナップ",
    copySelection: "選択図形をコピー",
    pasteSelection: "コピーした図形をペースト",
    duplicateSelection: "選択図形を複製",
  },
  styles: {
    black: "黒",
    gray: "グレー",
    red: "赤",
    blue: "青",
    green: "緑",
    orange: "オレンジ",
    purple: "紫",
  },
  paste: {
    position: "ペーストオプション",
    cursor: "カーソル位置",
    nearSource: "コピー元の近く（+5 mm）",
  },
  dialog: {
    value: {
      ariaLabel: (label: string) => `${label}の値`,
      inputMethod: "値の指定方法",
      fixed: "固定値",
      parameter: "パラメータ",
      degrees: "角度 (度)",
      millimeters: "値 (mm)",
      cancel: "キャンセル",
      confirm: "確定",
    },
    derived: {
      offset: "オフセット",
      fillet: "フィレット",
      value: (kind: "offset" | "fillet") => (kind === "offset" ? "オフセット" : "フィレット"),
      filletDescription: (count: number) => `選択した ${count} 件の連続する要素にフィレットを作成します。`,
      offsetSource: "オフセット元",
      selectedRange: (count: number) => `オフセット元: 選択範囲（${count} 件）`,
      inputMethod: "入力方法",
      parameterReference: "パラメータ参照",
      millimeters: "値 (mm)",
      apply: "適用",
      scopeNames: {
        singleElement: "単独要素",
        selectedRange: "選択範囲",
        closedContour: "閉じた輪郭",
      },
      parameterValue: (name: string, value: number) => `${name}（${value} mm）`,
    },
    layerDeletion: {
      ariaLabel: "レイヤー削除の確認",
      title: (name: string) => `「${name}」を削除しますか？`,
      impact: (name: string, count: number) =>
        `「${name}」には${count}件の図形または派生要素が紐づいています。削除すると、対象は残りのレイヤーへ移動します。`,
      cancel: "キャンセル",
      delete: "削除",
    },
    textEntry: { cancel: "キャンセル", apply: "適用" },
  },
  palette: {
    groupNames: { drawing: "作図", derived: "派生", constraint: "拘束", dimension: "寸法", measurement: "計測表示" },
    ariaLabel: "ツールパレット",
    title: "ツール",
    subtitle: "補助パレット",
    display: "ツール表示",
    showDetailed: "詳細ツールを表示",
    showBasicOnly: "基本ツールだけを表示",
    lineStyle: "型紙線種",
    lineStyleAria: "型紙線種",
    applyToSelection: "選択へ適用",
    roundHole: "丸穴",
    roundHoleKind: "穴種別",
    roundHoleDiameter: "丸穴の直径 (mm)",
    roundHoleKinds: {
      keyRing: "キーリング穴",
      rivet: "カシメ穴",
      snapFastener: "ジャンパーホック穴",
      decorative: "装飾穴",
    },
    activeDetailedTool: "使用中の詳細ツール",
  },
  workbench: {
    selection: "選択",
    constraint: "拘束",
    parameter: "パラメータ",
    noneSelected: "選択なし",
    selectOnCanvas: "キャンバス上の要素を選択してください。",
    noConstraints: "拘束なし",
    noParameters: "パラメータなし",
    none: "なし",
    unusedZero: "未使用 0 件",
    parameterSummary: (used: number, unused: number) => `使用 ${used} 件 / 未使用 ${unused} 件`,
    itemCount: (count: number) => `${count} 件`,
    layer: "レイヤー",
    shape: "図形",
  },
  menu: {
    section: {
      file: "ファイル",
      edit: "編集",
      drawing: "作図",
      constraint: "拘束",
      measurement: "計測",
      layer: "レイヤー",
      view: "表示",
    },
    item: {
      about: "KawaCADについて",
      openSourceLicenses: "OSSライセンス…",
      new: "新規プロジェクト",
      open: "開く…",
      save: "保存",
      saveAs: "別名で保存…",
      exportPDF: "PDF出力…",
      directPrint: "直接印刷…",
      undo: "元に戻す",
      redo: "やり直す",
      cut: "カット",
      copy: "コピー",
      paste: "ペースト",
      duplicate: "複製",
      delete: "削除",
      selectAll: "すべてを選択",
      cancelCurrentInteraction: "選択解除またはキャンセル",
      findInspector: "インスペクタ内を検索",
      smoothArcTangencies: "両端を接線化（試作）",
      measureSegmentLength: "線分長表示",
      toggleInspector: "インスペクタを表示／隠す",
      toggleBottomWorkbench: "サマリーを表示／隠す",
      inspectorShow: "インスペクタを表示",
      inspectorHide: "インスペクタを隠す",
      bottomWorkbenchShow: "サマリーを表示",
      bottomWorkbenchHide: "サマリーを隠す",
      toggleA4Orientation: "A4向きを切り替え",
      resetLayout: "レイアウトを初期状態に戻す",
      reload: "再読み込み",
    },
  },
  canvas: {
    outputPreview: "出力プレビュー",
    editDisplay: "編集表示",
    partOriginSelection: "パーツ原点を選択中",
    filletDraft: (count: number, closed: boolean) =>
      `フィレット対象 ${count} 件、${closed ? "閉じた輪郭" : "開いた輪郭"}`,
    arcStartSelection: "円弧の開始点を選択中",
    arcEndSelection: "円弧の終点を選択中",
    constraintTargetSelection: (count: number) => `拘束対象を ${count} 件選択中`,
    constraintHint: {
      target: "対象を選択",
      point: "点を選択",
      line: "線分を選択",
      circle: "円を選択",
      circleOrArc: "円/円弧を選択",
      pointOrLine: "点/線分を選択",
      pointOrCenter: "点/中心を選択",
      nextLine: "次: 線分",
      nextPoint: "次: 点",
      nextPointOrLine: "次: 点/線分",
      nextAxis: "次: 対称軸",
    },
    drawingNextPoint: "作図の次の点を選択中",
    drawingWaiting: "作図待機中",
    emptyTitle: "作図を始めましょう",
    emptyBody: "ツールを選択してキャンバスをクリックしてください。",
    dragMove: (count: number) => `${count}件を移動中`,
    dragCopy: (count: number) => `${count}件を複製中`,
    snapOff: "SNAP OFF",
    origin: "原点 0,0",
    scaleGuide: "50 mm",
    ariaLabel: "型紙作図キャンバス",
    editText: "テキストを編集",
    constraint: "拘束",
    interactionSummary: (tool: string, mode: string, selected: number, targets: number, description: string) =>
      `${tool}、${mode}、選択 ${selected} 件、拘束対象 ${targets} 件、${description}`,
  },
  licenses: {
    title: "OSSライセンス",
    loading: "読み込み中…",
  },
  toolbarMetrics: {
    zoom: (percent: number) => `倍率 ${percent}%`,
  },
  contextMenu: {
    convertMeasurement: "拘束へ変換",
    delete: "削除",
    editText: "テキストを編集",
    copy: "コピー",
    duplicate: "複製",
    smoothArcTangencies: "両端を接線化（試作）",
    paste: "ペースト",
    selectAll: "すべてを選択",
  },
  resize: { paletteWidth: "ツールパレットの幅" },
  inspector: {
    tab: {
      selection: "選択",
      layers: "レイヤー",
      sharedStyles: "共有スタイル",
      parameters: "パラメータ",
      parts: "パーツ",
    },
    ariaLabel: "インスペクタ",
    tabList: "インスペクタ項目",
    title: "インスペクタ",
    selectionSummary: (count: number) => `${count} 件を選択中`,
    selectedConstraint: "拘束を選択中",
    selectedMeasurement: "計測表示を選択中",
    selectedStitchStart: "縫い始め点を選択中",
    selectedText: "テキストを選択中",
    selectionChanged: "選択が変更されました",
    showSelection: "選択を表示",
    noSelection: "何も選択されていません",
    selection: "選択",
    kind: "種別",
    selectedGeometry: "図形",
    selectedLayer: "レイヤー",
    bulkStyle: "選択図形の共有スタイル",
    applyBulkStyle: "選択へ適用",
    createPartFromSelection: "選択図形からパーツを作成",
    constraint: "拘束",
    value: "値",
    measurementAndNotes: "計測と注記",
    annotationEdit: "注記を編集",
    annotation: "注記",
    layerVisible: "表示",
    partVisible: "表示",
    hidden: "非表示",
    edit: "編集",
    layerKinds: { cutLine: "カット線", dimension: "寸法", printGuide: "印刷ガイド", construction: "補助線" },
    drawingLayer: "作図レイヤー",
    layerSearch: "レイヤーを検索",
    includeInOutput: (name: string) => `${name} を出力対象に含める`,
    outputTarget: "出力対象",
    addLayer: "レイヤーを追加",
    sharedStyles: "共有スタイル",
    sharedStyleSearch: "共有スタイルを検索",
    styleName: "線種名",
    newStyle: "新規線種",
    name: "名称",
    addSharedStyle: "共有スタイル追加",
    noSharedStyles: "共有スタイルはまだありません",
    parameters: "パラメータ",
    add: "追加",
    parameterSearch: "パラメータを検索",
    noNamedParameters: "名前付きパラメータはまだありません",
    parameterUnused: "未使用",
    parameterUsage: (count: number) => `使用 ${count} 件`,
    parameterUnusedHint: "まだ拘束や派生要素から参照されていません",
    parameterUsedHint: (_count: number) => "拘束や派生要素から参照されています",
    deleteParameter: (name: string) => `${name} を削除`,
    deleteStyle: (name: string) => `${name} を削除`,
    parts: "パーツ",
    noParts: "パーツはまだありません。閉じた外形と内側の要素を選択して作成します。",
    partStructure: (outline: number, holes: number) => `外形 ${outline}図形・穴 ${holes}個`,
    partQuantityMembers: (quantity: number, members: number) => `必要数 ${quantity}・所属 ${members}`,
    alignDescription: "対象を2個以上選ぶと整列、3個以上で等間隔配置できます。",
    alignLeft: "左揃え",
    alignCenter: "横中央",
    alignRight: "右揃え",
    alignTop: "上揃え",
    alignBottom: "下揃え",
    alignVerticalCenter: "縦中央",
    distributeHorizontal: "水平に均等配置",
    distributeVertical: "垂直に均等配置",
    partLibrary: "パーツライブラリ",
    place: "配置",
    partLibraryEmpty: "登録済みパーツはありません",
    partLibraryQuantity: (quantity: number) => `必要数 ${quantity}`,
    document: "ドキュメント",
    viewMode: "表示モード",
    activeLayer: "作図レイヤー",
    visibleEntities: "表示図形",
    constraintCount: "拘束数",
    parameterCount: "パラメータ数",
    fixedValue: "固定値",
    millimeters: "値 (mm)",
    degrees: "度",
    measurementConstraint: "寸法拘束へ変換",
    stitchStartPoint: "縫い始め点",
    targetGeometry: "対象図形",
    content: "内容",
    textContent: "テキスト内容",
    textX: "テキスト X (mm)",
    textY: "テキスト Y (mm)",
    fontSize: "フォントサイズ (mm)",
    parameterName: "名前",
    parameterMemo: "メモ",
    unitMillimeter: "ミリメートル",
    colorPreset: "色プリセット",
    custom: "カスタム",
    color: "色",
    customColor: "カスタム色 (#RRGGBB)",
    lineWidthPreset: "線幅プリセット",
    lineWidth: "線幅",
    customLineWidth: "カスタム線幅 (mm)",
    lineStyle: "線種",
    lineStyles: { solid: "実線", dashed: "破線", dotted: "点線", construction: "補助線" },
    offsetElement: "オフセット線",
    filletElement: "フィレット",
    derivedElement: "派生要素",
    sourceCount: "参照元",
    distance: "距離 (mm)",
    radius: "半径 (mm)",
    layer: "レイヤー",
    noValue: "なし",
    direction: "方向",
    directions: { left: "左側", right: "右側", inward: "内側", outward: "外側" },
    reverseDirection: "方向を反転",
    geometry: "図形",
    derived: (kind: string) => kind,
    dimension: "寸法",
    diameter: "直径 (mm)",
    segmentLength: "線分長 (mm)",
    startAngle: "開始角 (度)",
    sweepAngle: "掃引角 (度)",
    setCurrentLengthConstraint: "現在長さを拘束",
    endPoint: "終点",
    partNameField: "パーツ名",
    quantity: "数量",
    partQuantity: (quantity: number) => `必要数: ${quantity}`,
    quantityOf: (name: string) => `${name} の数量`,
    partFixedHelp: "パーツの形状は固定されています。形状を編集するには、先にパーツを解除してください。",
    arrangementTarget: "整列・等間隔の対象",
    partPrintable: "印刷",
    originX: "位置 X mm",
    originY: "位置 Y mm",
    selectContents: "所属図形を選択",
    specifyOrigin: "キャンバスで位置を指定",
    libraryAdd: "ライブラリに登録",
    duplicatePart: "パーツを複製",
    detachPart: "パーツを解除",
    partDerivedMembers: "派生要素",
    partTextMembers: "注記",
    partMeasurementMembers: "計測表示",
    nameOf: (name: string) => `${name} の名前`,
    valueOf: (name: string) => `${name} の値 (mm)`,
    memoOf: (name: string) => `${name} のメモ`,
    configurationOf: (name: string) => `${name} の構成`,
    outputOf: (name: string) => `${name} を出力対象に含める`,
    originXOf: (name: string) => `${name} の原点 X (mm)`,
    originYOf: (name: string) => `${name} の原点 Y (mm)`,
    derivedSourceCount: (count: number) => `元図形 ${count}`,
    copyOf: (name: string) => `${name} のコピー`,
    derivedValue: (kind: string, label: string) => `${kind}の${label}`,
    geometryCount: {
      outline: (count: number) => `外形 ${count}`,
      holes: (count: number) => `穴 ${count}`,
      derived: (count: number) => `派生 ${count}`,
      text: (count: number) => `テキスト ${count}`,
      measurement: (count: number) => `計測 ${count}`,
    },
    parameter: "パラメータ",
    operationUpdated: (kind: string) => `${kind}を更新しました。`,
    parameterUpdated: (name: string) => `${name} を更新しました。`,
    roundHoleKind: "穴種別",
    constraintValue: (degrees: boolean) => `拘束値 (${degrees ? "度" : "mm"})`,
    parameterLinked: (kind: string) => `${kind}をパラメータに関連付けました。`,
    parameterReference: "パラメータ参照",
    selectGeometry: "選択図形",
    partName: "パーツ名",
    partVisibility: "パーツ表示",
    partOriginX: (name: string) => `${name} の原点 X (mm)`,
    partOriginY: (name: string) => `${name} の原点 Y (mm)`,
    partConfiguration: (name: string) => `${name} の構成`,
    partNameFor: (name: string) => `${name} の名前`,
    addSelection: "選択を追加",
    removeSelection: "選択を除外",
    setSelectionAsOutline: "選択を外形に設定",
    align: "整列",
    distribute: "均等配置",
    detach: "解除",
    unchanged: "変更なし",
    operationMessage: {
      constraintDeleted: "拘束を削除しました。",
      offsetUpdated: "オフセット線を更新しました。",
      filletUpdated: "フィレットを更新しました。",
      roundHoleDiameterUpdated: "丸穴の直径を更新しました。",
      roundHoleKindUpdated: "穴種別を更新しました。",
      segmentLengthUpdated: "線分長を更新しました。",
      circleRadiusUpdated: "円の半径を更新しました。",
      currentLengthConstrained: "現在の長さを拘束",
      quantity: "数量",
      arrangementTarget: "配置対象",
      originX: "原点 X (mm)",
      originY: "原点 Y (mm)",
      outline: "外形",
      holes: "穴",
      derivedCount: "派生",
      textCount: "テキスト",
      measurementCount: "計測",
      selectContents: "内容を選択",
      specifyOrigin: "原点を指定",
      libraryAdd: "ライブラリへ追加",
      copySuffix: "のコピー",
      unitCount: (count: number) => `${count} 件`,
      changeAngle: "角度を変更",
      changeDimension: "寸法を変更",
      dimensionMillimeters: "寸法 (mm)",
      angleDegrees: "角度 (度)",
      constraintUpdated: "拘束値を更新しました。",
      constraintParameterUpdated: "拘束パラメータを更新しました。",
      measurementUpdated: "計測表示を更新しました。",
      textUpdated: "テキストを更新しました。",
      parameterDeleted: (name: string) => `${name} を削除しました。`,
      sharedStyleDeleted: "共有スタイルを削除しました。",
      sharedStyleUpdated: "共有スタイルを更新しました。",
      sharedStyleAdded: "共有スタイルを追加しました。",
      layerVisibleUpdated: "レイヤー表示を更新しました。",
      layerOutputUpdated: "レイヤーの出力対象を更新しました。",
      layerStyleUpdated: "レイヤー線種を更新しました。",
      partOutputUpdated: "パーツの出力対象を更新しました。",
      partOriginUpdated: "パーツ原点を更新しました。",
      partAdded: "選択図形をパーツへ追加しました。",
      partRemoved: "選択図形をパーツから除外しました。",
      outlineUpdated: "パーツ外形を更新しました。",
      partNameUpdated: "パーツ名を更新しました。",
      partVisibilityUpdated: "パーツ表示を更新しました。",
      partMoved: "パーツを移動しました。",
      partDuplicated: "パーツを複製しました。",
      partDetached: "パーツを解除しました。",
      derivedLayerUpdated: "派生要素のレイヤーを更新しました。",
      derivedStyleUpdated: "派生要素の線種を更新しました。",
      offsetDirectionUpdated: "オフセット方向を更新しました。",
      geometryLayerUpdated: "図形レイヤーを更新しました。",
      geometryStyleUpdated: "図形線種を更新しました。",
      arcUpdated: "円弧を更新しました。",
      annotationUpdated: "注記を更新しました。",
      annotationDeleted: "計測表示を削除しました。",
      textDeleted: "テキストを削除しました。",
      layerDeleted: "レイヤーを削除しました。",
    },
    styleNameEdit: "線種名を変更",
  },
  app: {
    saveChangesTitle: (displayName: string) => `${displayName}の変更を保存しますか？`,
    saveChanges: "保存",
    productName: "KawaCAD",
    fileFilterName: "KawaCAD project",
    paperPortrait: "A4 Portrait",
    paperLandscape: "A4 Landscape",
    viewModeChanged: (output: boolean) => (output ? "出力プレビューに切り替えました。" : "編集表示に切り替えました。"),
    a4OrientationChanged: (landscape: boolean) => `A4基準表示を${landscape ? "横" : "縦"}向きにしました。`,
    selectGeometry: "図形を選択してください。",
    clickTarget: (tool: string) => `${tool}: 対象をクリックしてください。`,
    saved: (fileName: string) => `「${fileName}」に保存しました。`,
    reloaded: "ドキュメントを再読み込みしました。",
    undone: "取り消しました。",
    redone: "やり直しました。",
    smoothTangencies: "両端を接線化しました（試作）。",
    addLayerTitle: "レイヤーを追加",
    layerName: "レイヤー名",
    defaultLayerName: (number: number) => `レイヤー ${number}`,
    layerAdded: "レイヤーを追加しました。",
    layerDeleted: "レイヤーを削除しました。",
    createPartTitle: "パーツを作成",
    partName: "パーツ名",
    newPart: "新規パーツ",
    partCreated: "パーツを作成しました。",
    addParameterTitle: "パラメータを追加",
    parameterName: "パラメータ名",
    defaultParameterName: (number: number) => `param_${number}`,
    parameterAdded: "パラメータを追加しました。",
    renameLayerTitle: "レイヤー名を変更",
    layerNameUpdated: "レイヤー名を更新しました。",
    partQuantityTitle: "パーツ数量",
    partQuantity: "数量",
    partQuantityUpdated: "パーツ数量を更新しました。",
    styleUpdated: "選択図形の線種を更新しました。",
    entityCreated: (tool: string) => `${tool}を作成しました。`,
    dimensionConstraintAdded: "寸法拘束を追加しました。",
    currentSegmentLengthConstrained: "現在の線分長を拘束しました。",
    measurementAdded: (tool: string) => `${tool}を追加しました。`,
    noOffsetTarget: "オフセット対象がありません。",
    filletSourceRequired: "フィレット元を2件以上選択してください。",
    offsetAdded: "オフセットを追加しました。",
    filletUpdated: "フィレットを更新しました。",
    filletAdded: "フィレットを追加しました。",
    partOriginSet: "パーツ原点を設定しました。",
    roundHoleCreated: "丸穴を作成しました。",
    invalidRoundHoleDiameter: "丸穴の直径には正の有限値を入力してください。",
    stitchStartPointPlaced: "縫い始め点を配置しました。",
    addAnnotationTitle: "注記を追加",
    annotation: "注記",
    textAdded: "テキストを追加しました。",
    duplicatePreview: "複製プレビュー中",
    movePreview: "移動プレビュー中",
    preview: "プレビュー中",
    geometryDuplicated: "選択図形を複製しました。",
    geometryMoved: "選択図形を移動しました。",
    filletRadiusUpdated: "フィレット半径を更新しました。",
    controlPointMoved: "制御点を移動しました。",
    measurementMoved: "計測表示を移動しました。",
    dimensionMoved: "寸法拘束の表示を移動しました。",
    textMoved: "テキストを移動しました。",
    measurementDeleted: "計測表示を削除しました。",
    stitchStartPointDeleted: "縫い始め点を削除しました。",
    constraintDeleted: "拘束を削除しました。",
    textDeleted: "テキストを削除しました。",
    geometryDeleted: "選択図形を削除しました。",
    geometryCut: "選択図形を切り取りました。",
    geometryPasted: "コピーした図形を貼り付けました。",
    pastePositionChanged: "貼り付け位置を変更しました。",
    libraryPartPlaced: (name: string) => `「${name}」をライブラリから配置しました。`,
    alignmentUpdated: "パーツを整列しました。",
    distributionUpdated: "パーツを均等配置しました。",
    measurementConverted: "計測表示を寸法拘束へ変換しました。",
    measurementConvertedShort: "計測表示を寸法拘束に変換しました。",
    dirtyChanges: "未保存の変更があります。",
    saveAndCloseQuestion: "このウィンドウを閉じると、現在の未保存変更は失われます。",
    saveAndClose: "保存して閉じる",
    discardChanges: "変更を破棄",
    closeWithoutSaving: "保存せずに閉じる",
    cancel: "キャンセル",
    saveAndContinue: "保存して続行",
    continueWithoutSaving: "保存せずに続行",
    newProjectAction: "新規プロジェクトを作成すると、現在の未保存変更は失われます。",
    newProjectCreated: "新規プロジェクトを作成しました。",
    openOtherProjectAction: "別のプロジェクトを開くと、現在の未保存変更は失われます。",
    projectOpened: (fileName: string) => `「${fileName}」を開きました。`,
    untitled: "無題プロジェクト",
    undoRedo: (undo: boolean) => (undo ? "元に戻しました。" : "やり直しました。"),
    recoveryAria: "復旧候補",
    recoverySaveFailedTitle: "自動復旧データを保存できませんでした",
    recoveryChooserTitle: "復旧できる編集中データがあります",
    recoveryChooserMessage: "前回の終了前に保存されなかった編集中データを選んで確認できます。",
    recoveryBrokenCandidate: "破損した復旧候補",
    recoveryUnsavedSource: "未保存のドキュメント",
    recoveryUpdatedAt: (source: string, updatedAt: string) => `${source} / 最終復旧: ${updatedAt}`,
    showInFolder: "Finderに表示",
    recoveryNotice: (name: string) => `「${name}」の復旧用スナップショットがあります。`,
    recoveryOriginal: "保存前の変更を復元できます。",
    restore: "復旧して開く",
    discard: "破棄",
    later: "後で",
    toolDrawer: "ツール",
    statusSummaryHide: "サマリーを隠す",
    statusSummaryShow: "サマリーを表示",
    hud: (zoom: number, selected: number) => `${zoom}% · ${selected} 選択`,
    statusGeometry: (count: number) => `${count} 図形`,
    statusSelection: (count: number) => `${count} 選択`,
    statusNoSelection: "選択なし",
    statusCoordinates: (x: number, y: number) => `X ${x.toFixed(1)} / Y ${y.toFixed(1)} mm`,
    statusNoCoordinates: "座標 —",
    outputWarnings: (count: number) => `出力プレビュー: 警告 ${count} 件`,
    outputPages: (count: number) => `出力プレビュー: ${count} ページ`,
    unsaved: "未保存",
    unsavedChanges: "未保存の変更あり",
    savedState: "保存済み",
  },
  toolNames,
  toolHints,
  constraintLabels: {
    lineLineDistance: "線線距離",
  },
  constraintKindNames: {
    coincident: toolNames.coincident,
    horizontal: toolNames.horizontal,
    vertical: toolNames.vertical,
    parallel: toolNames.parallel,
    perpendicular: toolNames.perpendicular,
    tangent: toolNames.tangent,
    equalSegmentLength: toolNames.equalLength,
    angle: toolNames.angle,
    symmetric: toolNames.symmetric,
    pointOnLine: toolNames.pointOnLine,
    fixed: toolNames.fixed,
    distance: toolNames.distance,
    horizontalDistance: toolNames.horizontalDistance,
    verticalDistance: toolNames.verticalDistance,
    lineLineDistance: toolNames.lineLineDistance,
    segmentLength: toolNames.segmentLength,
    diameter: toolNames.diameter,
    radius: toolNames.radius,
  },
  measurementKindNames: {
    distance: toolNames.measureDistance,
    segmentLength: toolNames.measureSegmentLength,
    angle: toolNames.measureAngle,
    radius: toolNames.measureRadius,
    diameter: toolNames.measureDiameter,
    arcSweepAngle: toolNames.measureArcSweepAngle,
  },
  viewModeNames,
  constraintStatus,
} as const;

/** Common semantic keys shared with Swift's Localizable.strings. Platform-only
 * copy remains in each catalog, while this map makes the intentionally shared
 * surface executable and reviewable. */
export const sharedLocalizationKeyMap = {
  "app.document.untitled": "app.untitled",
  "app.status.created_new_document": "app.newProjectCreated",
  "output.destination.pdf": "output.pdf",
  "output.destination.direct_print": "output.directPrint",
  "output.sheet.destination": "output.destination",
  "output.sheet.paper": "output.paper",
  "output.sheet.scale": "output.scale",
  "output.sheet.scale_actual_size": "output.scaleActualSize",
  "output.sheet.page_count": "output.pageCount",
  "output.sheet.preview": "output.finalPreview",
  "output.sheet.preview_loading": "output.updating",
  "output.sheet.status": "output.status",
  "output.sheet.ready": "output.ready",
  "output.confirmation.save_with_warnings": "output.warningSaveNext",
  "output.confirmation.print_with_warnings": "output.warningPrintNext",
  "output.sheet.empty_output": "output.noOutput",
  "output.sheet.build_loading": "output.buildLoading",
  "output.sheet.printer": "output.printer",
  "document.save_confirmation.discard": "app.discardChanges",
  "document.save_confirmation.reason.close_window": "app.saveAndCloseQuestion",
  "document.recovery.chooser_title": "app.recoveryChooserTitle",
  "document.recovery.chooser_message": "app.recoveryChooserMessage",
  "document.recovery.recover": "app.restore",
  "document.recovery.discard": "app.discard",
  "document.recovery.later": "app.later",
  "document.recovery.unsaved_source": "app.recoveryUnsavedSource",
  "document.recovery.recovered_document": "error.recovery.restoreCompleted",
  "workbench.select_on_canvas": "workbench.selectOnCanvas",
  "toolbar.grid": "toolbar.grid",
  "toolbar.a4": "toolbar.a4Reference",
  "toolbar.grid_snap": "toolbar.gridSnap",
  "toolbar.point_snap": "toolbar.pointSnap",
  "menu.reload": "menu.item.reload",
  "menu.add_layer": "inspector.addLayer",
  "canvas.menu.copy_selection": "contextMenu.copy",
  "canvas.menu.duplicate_selection": "contextMenu.duplicate",
  "canvas.menu.delete_selection": "contextMenu.delete",
  "canvas.menu.paste_copied": "contextMenu.paste",
  "canvas.menu.select_all": "contextMenu.selectAll",
  "canvas.origin_label": "canvas.origin",
  "canvas.scale_guide_label": "canvas.scaleGuide",
  "inspector.tab.parts": "inspector.tab.parts",
  "inspector.parts": "inspector.parts",
  "inspector.no_parts": "inspector.noParts",
  "inspector.visible_entities": "inspector.visibleEntities",
  "inspector.add_layer": "inspector.addLayer",
  "inspector.shared_styles": "inspector.sharedStyles",
  "inspector.distribute_horizontal": "inspector.distributeHorizontal",
  "inspector.distribute_vertical": "inspector.distributeVertical",
  "inspector.create_part_from_selection": "inspector.createPartFromSelection",
  "inspector.part_fixed_help": "inspector.partFixedHelp",
  "tool.select": "toolNames.select",
  "tool.point": "toolNames.point",
  "tool.line": "toolNames.line",
  "tool.circle": "toolNames.circle",
  "tool.round_hole": "toolNames.roundHole",
  "tool.arc": "toolNames.arc",
  "tool.stitch_start_point": "toolNames.stitchStartPoint",
  "tool.center_line": "toolNames.centerLine",
  "tool.horizontal_center_line": "toolNames.horizontalCenterLine",
  "tool.vertical_center_line": "toolNames.verticalCenterLine",
  "tool.coincident": "toolNames.coincident",
  "tool.horizontal": "toolNames.horizontal",
  "tool.vertical": "toolNames.vertical",
  "tool.parallel": "toolNames.parallel",
  "tool.perpendicular": "toolNames.perpendicular",
  "tool.tangent": "toolNames.tangent",
  "tool.equal_length": "toolNames.equalLength",
  "tool.angle": "toolNames.angle",
  "tool.symmetric": "toolNames.symmetric",
  "tool.point_on_line": "toolNames.pointOnLine",
  "tool.fixed": "toolNames.fixed",
  "tool.distance": "toolNames.distance",
  "tool.horizontal_distance": "toolNames.horizontalDistance",
  "tool.vertical_distance": "toolNames.verticalDistance",
  "tool.line_line_distance": "constraintLabels.lineLineDistance",
  "tool.segment_length": "toolNames.segmentLength",
  "tool.diameter": "toolNames.diameter",
  "tool.radius": "toolNames.radius",
  "tool.offset": "toolNames.offset",
  "tool.fillet": "toolNames.fillet",
  "tool.free_text": "toolNames.freeText",
  "tool.measure_distance": "toolNames.measureDistance",
  "tool.measure_segment_length": "toolNames.measureSegmentLength",
  "tool.measure_angle": "toolNames.measureAngle",
  "tool.measure_radius": "toolNames.measureRadius",
  "tool.measure_diameter": "toolNames.measureDiameter",
  "tool.measure_arc_sweep_angle": "toolNames.measureArcSweepAngle",
  "view_mode.edit_display": "viewModeNames.editDisplay",
  "view_mode.output_preview": "viewModeNames.outputPreview",
  "constraint_status.unknown": "constraintStatus.unknown",
  "constraint_status.under_constrained": "constraintStatus.underConstrained",
  "constraint_status.fully_constrained": "constraintStatus.fullyConstrained",
  "constraint_status.over_constrained": "constraintStatus.overConstrained",
  "constraint_status.conflicting": "constraintStatus.conflicting",
  "app.annotation": "app.annotation",
  "style.color.black": "styles.black",
  "style.color.gray": "styles.gray",
  "style.color.red": "styles.red",
  "style.color.blue": "styles.blue",
  "style.color.green": "styles.green",
  "style.color.orange": "styles.orange",
  "style.color.purple": "styles.purple",
  "derived.direction.left": "inspector.directions.left",
  "derived.direction.right": "inspector.directions.right",
  "derived.direction.inward": "inspector.directions.inward",
  "derived.direction.outward": "inspector.directions.outward",
  "derived.kind.offset": "inspector.offsetElement",
  "derived.kind.fillet": "inspector.filletElement",
  "status.offset_distance": "status.offsetDistance",
  "status.line_width": "status.lineWidth",
  "workbench.no_constraints": "workbench.noConstraints",
  "workbench.constraint": "workbench.constraint",
  "workbench.parameter": "workbench.parameter",
  "workbench.none_selected": "workbench.noneSelected",
  "workbench.no_parameters": "workbench.noParameters",
  "workbench.none": "workbench.none",
  "workbench.unused_zero": "workbench.unusedZero",
  "workbench.layer": "workbench.layer",
  "inspector.selection_changed": "inspector.selectionChanged",
  "inspector.no_selection": "inspector.noSelection",
  "inspector.no_shared_styles": "inspector.noSharedStyles",
  "inspector.no_named_parameters": "inspector.noNamedParameters",
  "inspector.add_shared_style": "inspector.addSharedStyle",
  "inspector.layer_visible": "inspector.layerVisible",
  "inspector.part_visible": "inspector.partVisible",
  "inspector.part_library_empty": "inspector.partLibraryEmpty",
} as const;

/** Keys whose names are intentionally aligned with Swift's catalog. The
 * comparison ignores snake_case/camelCase and Tauri's object nesting, but it
 * does not ignore different meanings or duplicate aliases. */
export const alignedLocalizationKeyMap = {
  "constraint_status.unknown": "constraintStatus.unknown",
  "constraint_status.under_constrained": "constraintStatus.underConstrained",
  "constraint_status.fully_constrained": "constraintStatus.fullyConstrained",
  "constraint_status.over_constrained": "constraintStatus.overConstrained",
  "constraint_status.conflicting": "constraintStatus.conflicting",
  "workbench.selection": "workbench.selection",
  "workbench.constraint": "workbench.constraint",
  "workbench.parameter": "workbench.parameter",
  "workbench.none_selected": "workbench.noneSelected",
  "workbench.select_on_canvas": "workbench.selectOnCanvas",
  "workbench.no_constraints": "workbench.noConstraints",
  "workbench.no_parameters": "workbench.noParameters",
  "workbench.none": "workbench.none",
  "workbench.unused_zero": "workbench.unusedZero",
  "workbench.parameter_summary": "workbench.parameterSummary",
  "workbench.item_count": "workbench.itemCount",
  "workbench.layer": "workbench.layer",
  "inspector.tab.selection": "inspector.tab.selection",
  "inspector.tab.layers": "inspector.tab.layers",
  "inspector.tab.shared_styles": "inspector.tab.sharedStyles",
  "inspector.tab.parameters": "inspector.tab.parameters",
  "inspector.tab.parts": "inspector.tab.parts",
  "inspector.selection_changed": "inspector.selectionChanged",
  "inspector.no_selection": "inspector.noSelection",
  "inspector.no_shared_styles": "inspector.noSharedStyles",
  "inspector.no_named_parameters": "inspector.noNamedParameters",
  "inspector.add_shared_style": "inspector.addSharedStyle",
  "inspector.layer_visible": "inspector.layerVisible",
  "inspector.part_visible": "inspector.partVisible",
  "inspector.part_library_empty": "inspector.partLibraryEmpty",
  "inspector.visible_entities": "inspector.visibleEntities",
} as const;

export { appStrings };
